# Generated by Django 5.1 on 2024-08-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='grade',
            field=models.CharField(default=1, max_length=10, verbose_name='grade'),
            preserve_default=False,
        ),
    ]
