# Generated by Django 5.1 on 2024-08-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_testscorethroughmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parenting_style',
            field=models.CharField(default='Supportive', max_length=150, verbose_name='parenting style'),
        ),
    ]
